package app.view;

/*
Authors: Jaiveer Katariya, Jongho Shin, Kyle Harvey

This class is used to generate the slider object that appears in the ControlView object which allows the user to control
the speed of the simulation. It assumes that the user possesses the following dependencies/packages:
app.controller.SimulationController;
javafx.scene.control.Slider;

This class is used in the ControlView class, and to use it, one would simply need to declare
it with the parameters specified by the constructor.

*/

import app.controller.SimulationController;
import javafx.scene.control.Slider;

public class SpeedSlider {
    private static final int MIN_FRAMES = 1;
    private static final int MAX_FRAMES = 10;
    private Slider mySlider;
    private SimulationController mySimulationController;

    /**
     * Constructor to generate new slider GUI component
     *
     * @param sc SimulationController object that represents current simulation's SimulationController
     */
    public SpeedSlider(SimulationController sc){
        mySimulationController = sc;
        makeSlider();
    }
    private void makeSlider() {

        mySlider = new Slider();

        mySlider.setShowTickLabels(true);
        mySlider.setMin(MIN_FRAMES);
        mySlider.setMax(MAX_FRAMES);
        mySlider.setValue(mySimulationController.getMyFramesPerSecond());
        mySlider.valueProperty().addListener((observableValue, number, t1) -> mySimulationController.setMyFramesPerSecond(t1.intValue()));
    }

    /**
     * Method to return the JavaFX slider object generated by the class
     *
     * @return a slider that is designed to appear in ControlView
     */

    public Slider getMySlider(){return mySlider;}
}
